# Generated by Django 3.2.2 on 2021-08-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_researcher',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_user',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.SmallIntegerField(default=0, verbose_name='Role \n [0] User \n [1] Researcher]'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
