# Generated by Django 3.2.2 on 2021-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210806_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.SmallIntegerField(default=0, verbose_name='Option: \n [0] User \n [1] Researcher \n Your role number is'),
        ),
    ]
