# Generated by Django 3.2.2 on 2021-08-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_account_hash_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash_value',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
