# Generated by Django 3.2.2 on 2021-08-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_account_hash_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherModel',
            fields=[
                ('id_researcher', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(blank=True, default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolHistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
