# Generated by Django 3.2.2 on 2021-08-10 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20210810_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchermodel',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
