# Generated by Django 3.2.2 on 2021-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_researchermodel_dt_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(default=False, primary_key=True, serialize=False),
        ),
    ]
