# Generated by Django 3.2.2 on 2021-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_symbolhistorydata_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolhistorydata',
            name='kline_size',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
