# Generated by Django 3.2.2 on 2021-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_symbolhistorydata_kline_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolhistorydata',
            name='volume',
            field=models.FloatField(default=False),
        ),
    ]
