# Generated by Django 3.2.2 on 2021-08-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_symbolhistorydata_volume'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='symbolhistorydata',
            unique_together={('symbol', 'datetime')},
        ),
    ]
